import React from 'react';
import { Container, Typography, Paper } from '@mui/material';

const LLMGeneratedCode = () => {
    const codeExample = `// Example of code generated by the LLM for handling user login
app.post('/login', (req, res) => {
    const { username, password } = req.body;
    pool.getConnection((err, connection) => {
        if (err) throw err;
        const query = "SELECT id, username, password FROM users WHERE username = ?";
        connection.query(query, [username], (error, results) => {
            connection.release();
            if (results.length) {
                const user = results[0];
                if (bcrypt.compareSync(password, user.password)) {
                    req.session.user_id = user.id; // Store user ID in the session
                    req.session.username = user.username;
                    const sessionId = uuid.v4();
                    pool.getConnection((err, connection) => {
                        if (err) throw err;
                        const sessionQuery = "INSERT INTO sessions (username, session_id) VALUES (?, ?)";
                        connection.query(sessionQuery, [username, sessionId], (err) => {
                            connection.release();
                            if (err) throw err;
                            res.cookie("session_id", sessionId).json({ success: true });
                        });
                    });
                } else {
                    res.status(401).json({ error: 'Invalid credentials' });
                }
            } else {
                res.status(401).json({ error: 'Invalid credentials' });
            }
        });
    });
});`;

    return (
        <Container>
            <Typography variant="h4" gutterBottom>
                LLM Generated Code
            </Typography>
            <Typography variant="body1" gutterBottom>
                This page provides an example of the code generated by the LLM for this project.
            </Typography>
            <Paper elevation={3} style={{ padding: '16px', backgroundColor: '#f5f5f5' }}>
                <pre>
                    <code>
                        {codeExample}
                    </code>
                </pre>
            </Paper>
        </Container>
    );
};

export default LLMGeneratedCode;
